-- Mostrador ágil: código de barras + catálogo maestro para autocompletar.
--
-- Dos cosas distintas que conviene no mezclar:
--   codigo         → el que usa el ferretero ("T440", "MECHA6"). Ya existía, es
--                    obligatorio y único por negocio.
--   codigo_barras  → el EAN-13 impreso por el fabricante. Es opcional: la mitad
--                    de lo que se vende en una ferretería (tornillos sueltos,
--                    cable por metro) no tiene código de barras.
-- El lector busca por los dos, así que el que use el EAN como código interno
-- también funciona sin cargar nada acá.

ALTER TABLE herramientas ADD COLUMN codigo_barras TEXT;

-- Parcial: dos productos sin EAN no chocan entre sí, pero un mismo EAN no se
-- puede repetir dentro de un negocio (si no, el lector no sabría cuál cargar).
CREATE UNIQUE INDEX idx_herramientas_barras
  ON herramientas (negocio_id, codigo_barras)
  WHERE codigo_barras IS NOT NULL;

-- Índice para el lector: tiene que resolver en un teclazo.
CREATE INDEX idx_herramientas_codigo ON herramientas (negocio_id, codigo);

/*
 * Catálogo maestro: artículos comunes de ferretería, para que al tipear el
 * nombre se autocomplete y no haya que escribirlo entero ni pensar el rubro.
 *
 * A PROPÓSITO NO TIENE negocio_id. Es una tabla de referencia compartida, de
 * sólo lectura para los negocios: no guarda ni precios ni stock ni nada de
 * nadie. Por eso no entra en la auditoría de aislamiento (scripts/auditar-
 * aislamiento.mjs) — no hay datos de un negocio que se puedan filtrar a otro.
 * Lo único que viaja del catálogo a la ficha del producto es texto (nombre y
 * rubro), y sólo cuando el usuario lo elige.
 */
CREATE TABLE catalogo_maestro (
  id            INTEGER PRIMARY KEY AUTOINCREMENT,
  nombre        TEXT NOT NULL,
  rubro         TEXT NOT NULL,
  -- Nombre sin acentos y en minúscula: es por acá que se busca, para que
  -- "mecha widia" encuentre "Mecha Widia" y "cañeria" encuentre "Cañería".
  busqueda      TEXT NOT NULL,
  -- Cuántas veces alguien lo eligió. Ordena las sugerencias por lo que la
  -- gente realmente usa, no alfabéticamente.
  veces_usado   INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX idx_catalogo_busqueda ON catalogo_maestro (busqueda);
CREATE INDEX idx_catalogo_usado    ON catalogo_maestro (veces_usado DESC);

-- Semilla inicial: 240 artículos habituales de ferretería.
-- Es un punto de partida, no una verdad: cada negocio le agrega los suyos
-- al crear productos, y el contador veces_usado sube lo que más se elige.
INSERT INTO catalogo_maestro (nombre, rubro, busqueda) VALUES
  ('Tornillo autoperforante', 'Tornillería', 'tornillo autoperforante'),
  ('Tornillo cabeza plana', 'Tornillería', 'tornillo cabeza plana'),
  ('Tornillo cabeza fresada', 'Tornillería', 'tornillo cabeza fresada'),
  ('Tornillo para madera', 'Tornillería', 'tornillo para madera'),
  ('Tornillo para aglomerado', 'Tornillería', 'tornillo para aglomerado'),
  ('Tornillo Parker', 'Tornillería', 'tornillo parker'),
  ('Tornillo mecánico', 'Tornillería', 'tornillo mecanico'),
  ('Tornillo Allen', 'Tornillería', 'tornillo allen'),
  ('Tornillo de fijación', 'Tornillería', 'tornillo de fijacion'),
  ('Tuerca hexagonal', 'Tornillería', 'tuerca hexagonal'),
  ('Tuerca mariposa', 'Tornillería', 'tuerca mariposa'),
  ('Tuerca ciega', 'Tornillería', 'tuerca ciega'),
  ('Bulón hexagonal', 'Tornillería', 'bulon hexagonal'),
  ('Bulón con tuerca', 'Tornillería', 'bulon con tuerca'),
  ('Arandela plana', 'Tornillería', 'arandela plana'),
  ('Arandela grower', 'Tornillería', 'arandela grower'),
  ('Arandela de presión', 'Tornillería', 'arandela de presion'),
  ('Remache pop', 'Tornillería', 'remache pop'),
  ('Clavo de acero', 'Tornillería', 'clavo de acero'),
  ('Clavo punta París', 'Tornillería', 'clavo punta paris'),
  ('Clavo para hormigón', 'Tornillería', 'clavo para hormigon'),
  ('Tarugo plástico', 'Tornillería', 'tarugo plastico'),
  ('Tarugo con tornillo', 'Tornillería', 'tarugo con tornillo'),
  ('Tarugo de expansión', 'Tornillería', 'tarugo de expansion'),
  ('Brocha de anclaje', 'Tornillería', 'brocha de anclaje'),
  ('Grampa omega', 'Tornillería', 'grampa omega'),
  ('Espárrago roscado', 'Tornillería', 'esparrago roscado'),
  ('Varilla roscada', 'Tornillería', 'varilla roscada'),
  ('Martillo carpintero', 'Herramientas manuales', 'martillo carpintero'),
  ('Martillo de bola', 'Herramientas manuales', 'martillo de bola'),
  ('Maza de goma', 'Herramientas manuales', 'maza de goma'),
  ('Destornillador Phillips', 'Herramientas manuales', 'destornillador phillips'),
  ('Destornillador paleta', 'Herramientas manuales', 'destornillador paleta'),
  ('Juego de destornilladores', 'Herramientas manuales', 'juego de destornilladores'),
  ('Pinza universal', 'Herramientas manuales', 'pinza universal'),
  ('Pinza de punta', 'Herramientas manuales', 'pinza de punta'),
  ('Pinza pico de loro', 'Herramientas manuales', 'pinza pico de loro'),
  ('Pinza corta cable', 'Herramientas manuales', 'pinza corta cable'),
  ('Alicate', 'Herramientas manuales', 'alicate'),
  ('Llave ajustable', 'Herramientas manuales', 'llave ajustable'),
  ('Llave francesa', 'Herramientas manuales', 'llave francesa'),
  ('Llave stilson', 'Herramientas manuales', 'llave stilson'),
  ('Juego de llaves combinadas', 'Herramientas manuales', 'juego de llaves combinadas'),
  ('Juego de llaves Allen', 'Herramientas manuales', 'juego de llaves allen'),
  ('Serrucho', 'Herramientas manuales', 'serrucho'),
  ('Sierra de arco', 'Herramientas manuales', 'sierra de arco'),
  ('Hoja de sierra', 'Herramientas manuales', 'hoja de sierra'),
  ('Formón', 'Herramientas manuales', 'formon'),
  ('Cepillo de carpintero', 'Herramientas manuales', 'cepillo de carpintero'),
  ('Cincel', 'Herramientas manuales', 'cincel'),
  ('Punzón', 'Herramientas manuales', 'punzon'),
  ('Lima plana', 'Herramientas manuales', 'lima plana'),
  ('Lima redonda', 'Herramientas manuales', 'lima redonda'),
  ('Escofina', 'Herramientas manuales', 'escofina'),
  ('Tenaza', 'Herramientas manuales', 'tenaza'),
  ('Cutter', 'Herramientas manuales', 'cutter'),
  ('Tijera de chapa', 'Herramientas manuales', 'tijera de chapa'),
  ('Espátula', 'Herramientas manuales', 'espatula'),
  ('Llana', 'Herramientas manuales', 'llana'),
  ('Fratacho', 'Herramientas manuales', 'fratacho'),
  ('Plomada', 'Herramientas manuales', 'plomada'),
  ('Nivel de burbuja', 'Herramientas manuales', 'nivel de burbuja'),
  ('Escuadra', 'Herramientas manuales', 'escuadra'),
  ('Cinta métrica', 'Herramientas manuales', 'cinta metrica'),
  ('Metro plegable', 'Herramientas manuales', 'metro plegable'),
  ('Prensa sargento', 'Herramientas manuales', 'prensa sargento'),
  ('Morsa de banco', 'Herramientas manuales', 'morsa de banco'),
  ('Arco de sierra', 'Herramientas manuales', 'arco de sierra'),
  ('Cable unipolar', 'Electricidad', 'cable unipolar'),
  ('Cable taller', 'Electricidad', 'cable taller'),
  ('Cable bipolar', 'Electricidad', 'cable bipolar'),
  ('Cable coaxil', 'Electricidad', 'cable coaxil'),
  ('Ficha macho', 'Electricidad', 'ficha macho'),
  ('Ficha hembra', 'Electricidad', 'ficha hembra'),
  ('Toma corriente', 'Electricidad', 'toma corriente'),
  ('Llave de un punto', 'Electricidad', 'llave de un punto'),
  ('Llave combinación', 'Electricidad', 'llave combinacion'),
  ('Llave térmica', 'Electricidad', 'llave termica'),
  ('Disyuntor diferencial', 'Electricidad', 'disyuntor diferencial'),
  ('Caja de embutir', 'Electricidad', 'caja de embutir'),
  ('Caja estanca', 'Electricidad', 'caja estanca'),
  ('Tablero eléctrico', 'Electricidad', 'tablero electrico'),
  ('Portalámpara', 'Electricidad', 'portalampara'),
  ('Lámpara LED', 'Electricidad', 'lampara led'),
  ('Tubo LED', 'Electricidad', 'tubo led'),
  ('Reflector LED', 'Electricidad', 'reflector led'),
  ('Prolongador', 'Electricidad', 'prolongador'),
  ('Zapatilla eléctrica', 'Electricidad', 'zapatilla electrica'),
  ('Cinta aisladora', 'Electricidad', 'cinta aisladora'),
  ('Precintos plásticos', 'Electricidad', 'precintos plasticos'),
  ('Terminal de ojal', 'Electricidad', 'terminal de ojal'),
  ('Canaleta plástica', 'Electricidad', 'canaleta plastica'),
  ('Caño corrugado', 'Electricidad', 'cano corrugado'),
  ('Timbre', 'Electricidad', 'timbre'),
  ('Sensor de movimiento', 'Electricidad', 'sensor de movimiento'),
  ('Fotocélula', 'Electricidad', 'fotocelula'),
  ('Buscapolo', 'Electricidad', 'buscapolo'),
  ('Pinza amperométrica', 'Electricidad', 'pinza amperometrica'),
  ('Tester digital', 'Electricidad', 'tester digital'),
  ('Caño PVC', 'Plomería', 'cano pvc'),
  ('Caño de polipropileno', 'Plomería', 'cano de polipropileno'),
  ('Codo PVC', 'Plomería', 'codo pvc'),
  ('Te PVC', 'Plomería', 'te pvc'),
  ('Cupla PVC', 'Plomería', 'cupla pvc'),
  ('Unión doble', 'Plomería', 'union doble'),
  ('Reducción PVC', 'Plomería', 'reduccion pvc'),
  ('Canilla de bronce', 'Plomería', 'canilla de bronce'),
  ('Canilla de jardín', 'Plomería', 'canilla de jardin'),
  ('Grifería de cocina', 'Plomería', 'griferia de cocina'),
  ('Grifería de baño', 'Plomería', 'griferia de bano'),
  ('Flexible de conexión', 'Plomería', 'flexible de conexion'),
  ('Válvula esférica', 'Plomería', 'valvula esferica'),
  ('Llave de paso', 'Plomería', 'llave de paso'),
  ('Rejilla de piso', 'Plomería', 'rejilla de piso'),
  ('Sifón', 'Plomería', 'sifon'),
  ('Sopapa', 'Plomería', 'sopapa'),
  ('Flotante de tanque', 'Plomería', 'flotante de tanque'),
  ('Cinta teflón', 'Plomería', 'cinta teflon'),
  ('Sellador de roscas', 'Plomería', 'sellador de roscas'),
  ('Junta de goma', 'Plomería', 'junta de goma'),
  ('Aro de cera', 'Plomería', 'aro de cera'),
  ('Mochila de inodoro', 'Plomería', 'mochila de inodoro'),
  ('Tanque de agua', 'Plomería', 'tanque de agua'),
  ('Bomba presurizadora', 'Plomería', 'bomba presurizadora'),
  ('Termofusora', 'Plomería', 'termofusora'),
  ('Látex interior', 'Pinturería', 'latex interior'),
  ('Látex exterior', 'Pinturería', 'latex exterior'),
  ('Esmalte sintético', 'Pinturería', 'esmalte sintetico'),
  ('Esmalte al agua', 'Pinturería', 'esmalte al agua'),
  ('Antióxido', 'Pinturería', 'antioxido'),
  ('Convertidor de óxido', 'Pinturería', 'convertidor de oxido'),
  ('Barniz', 'Pinturería', 'barniz'),
  ('Impregnante para madera', 'Pinturería', 'impregnante para madera'),
  ('Fijador sellador', 'Pinturería', 'fijador sellador'),
  ('Pintura para piletas', 'Pinturería', 'pintura para piletas'),
  ('Pintura para pisos', 'Pinturería', 'pintura para pisos'),
  ('Membrana líquida', 'Pinturería', 'membrana liquida'),
  ('Aguarrás', 'Pinturería', 'aguarras'),
  ('Thinner', 'Pinturería', 'thinner'),
  ('Diluyente', 'Pinturería', 'diluyente'),
  ('Rodillo de lana', 'Pinturería', 'rodillo de lana'),
  ('Rodillo espuma', 'Pinturería', 'rodillo espuma'),
  ('Bandeja para rodillo', 'Pinturería', 'bandeja para rodillo'),
  ('Pincel', 'Pinturería', 'pincel'),
  ('Brocha', 'Pinturería', 'brocha'),
  ('Cinta de papel', 'Pinturería', 'cinta de papel'),
  ('Cinta de enmascarar', 'Pinturería', 'cinta de enmascarar'),
  ('Lija al agua', 'Pinturería', 'lija al agua'),
  ('Lija para madera', 'Pinturería', 'lija para madera'),
  ('Masilla plástica', 'Pinturería', 'masilla plastica'),
  ('Enduido plástico', 'Pinturería', 'enduido plastico'),
  ('Sellador acrílico', 'Pinturería', 'sellador acrilico'),
  ('Silicona', 'Pinturería', 'silicona'),
  ('Cemento', 'Construcción', 'cemento'),
  ('Cal hidratada', 'Construcción', 'cal hidratada'),
  ('Cal aérea', 'Construcción', 'cal aerea'),
  ('Arena fina', 'Construcción', 'arena fina'),
  ('Arena gruesa', 'Construcción', 'arena gruesa'),
  ('Piedra partida', 'Construcción', 'piedra partida'),
  ('Hidrófugo', 'Construcción', 'hidrofugo'),
  ('Ladrillo hueco', 'Construcción', 'ladrillo hueco'),
  ('Ladrillo común', 'Construcción', 'ladrillo comun'),
  ('Bloque de hormigón', 'Construcción', 'bloque de hormigon'),
  ('Hierro aletado', 'Construcción', 'hierro aletado'),
  ('Malla soldada', 'Construcción', 'malla soldada'),
  ('Alambre de atar', 'Construcción', 'alambre de atar'),
  ('Pegamento para cerámica', 'Construcción', 'pegamento para ceramica'),
  ('Pastina', 'Construcción', 'pastina'),
  ('Yeso', 'Construcción', 'yeso'),
  ('Placa de yeso', 'Construcción', 'placa de yeso'),
  ('Perfil montante', 'Construcción', 'perfil montante'),
  ('Perfil solera', 'Construcción', 'perfil solera'),
  ('Membrana asfáltica', 'Construcción', 'membrana asfaltica'),
  ('Chapa acanalada', 'Construcción', 'chapa acanalada'),
  ('Chapa lisa', 'Construcción', 'chapa lisa'),
  ('Machimbre', 'Construcción', 'machimbre'),
  ('Tirante de pino', 'Construcción', 'tirante de pino'),
  ('Fenólico', 'Construcción', 'fenolico'),
  ('Taladro percutor', 'Máquinas y accesorios', 'taladro percutor'),
  ('Taladro atornillador', 'Máquinas y accesorios', 'taladro atornillador'),
  ('Amoladora angular', 'Máquinas y accesorios', 'amoladora angular'),
  ('Sierra circular', 'Máquinas y accesorios', 'sierra circular'),
  ('Sierra caladora', 'Máquinas y accesorios', 'sierra caladora'),
  ('Lijadora orbital', 'Máquinas y accesorios', 'lijadora orbital'),
  ('Soldadora inverter', 'Máquinas y accesorios', 'soldadora inverter'),
  ('Compresor de aire', 'Máquinas y accesorios', 'compresor de aire'),
  ('Hidrolavadora', 'Máquinas y accesorios', 'hidrolavadora'),
  ('Aspiradora', 'Máquinas y accesorios', 'aspiradora'),
  ('Pistola de calor', 'Máquinas y accesorios', 'pistola de calor'),
  ('Mecha para metal', 'Máquinas y accesorios', 'mecha para metal'),
  ('Mecha para madera', 'Máquinas y accesorios', 'mecha para madera'),
  ('Mecha widia', 'Máquinas y accesorios', 'mecha widia'),
  ('Mecha para hormigón', 'Máquinas y accesorios', 'mecha para hormigon'),
  ('Disco de corte', 'Máquinas y accesorios', 'disco de corte'),
  ('Disco de desbaste', 'Máquinas y accesorios', 'disco de desbaste'),
  ('Disco diamantado', 'Máquinas y accesorios', 'disco diamantado'),
  ('Fresa', 'Máquinas y accesorios', 'fresa'),
  ('Punta de atornillar', 'Máquinas y accesorios', 'punta de atornillar'),
  ('Adaptador de puntas', 'Máquinas y accesorios', 'adaptador de puntas'),
  ('Batería recargable', 'Máquinas y accesorios', 'bateria recargable'),
  ('Cargador de batería', 'Máquinas y accesorios', 'cargador de bateria'),
  ('Candado', 'Ferretería general', 'candado'),
  ('Cerradura', 'Ferretería general', 'cerradura'),
  ('Cerrojo', 'Ferretería general', 'cerrojo'),
  ('Pasador', 'Ferretería general', 'pasador'),
  ('Bisagra', 'Ferretería general', 'bisagra'),
  ('Bisagra a cazoleta', 'Ferretería general', 'bisagra a cazoleta'),
  ('Manija', 'Ferretería general', 'manija'),
  ('Picaporte', 'Ferretería general', 'picaporte'),
  ('Ruedita', 'Ferretería general', 'ruedita'),
  ('Riel para cajón', 'Ferretería general', 'riel para cajon'),
  ('Corredera', 'Ferretería general', 'corredera'),
  ('Gancho', 'Ferretería general', 'gancho'),
  ('Alcayata', 'Ferretería general', 'alcayata'),
  ('Cadena', 'Ferretería general', 'cadena'),
  ('Soga', 'Ferretería general', 'soga'),
  ('Piola', 'Ferretería general', 'piola'),
  ('Cinta de embalar', 'Ferretería general', 'cinta de embalar'),
  ('Adhesivo instantáneo', 'Ferretería general', 'adhesivo instantaneo'),
  ('Cola vinílica', 'Ferretería general', 'cola vinilica'),
  ('Adhesivo de contacto', 'Ferretería general', 'adhesivo de contacto'),
  ('Espuma de poliuretano', 'Ferretería general', 'espuma de poliuretano'),
  ('Grasa', 'Ferretería general', 'grasa'),
  ('Aceite lubricante', 'Ferretería general', 'aceite lubricante'),
  ('Lubricante en aerosol', 'Ferretería general', 'lubricante en aerosol'),
  ('Wd-40', 'Ferretería general', 'wd-40'),
  ('Balde', 'Ferretería general', 'balde'),
  ('Carretilla', 'Ferretería general', 'carretilla'),
  ('Pala', 'Ferretería general', 'pala'),
  ('Pala de punta', 'Ferretería general', 'pala de punta'),
  ('Rastrillo', 'Ferretería general', 'rastrillo'),
  ('Manguera de jardín', 'Ferretería general', 'manguera de jardin'),
  ('Regadera', 'Ferretería general', 'regadera'),
  ('Escalera', 'Ferretería general', 'escalera'),
  ('Guantes de trabajo', 'Ferretería general', 'guantes de trabajo'),
  ('Anteojos de seguridad', 'Ferretería general', 'anteojos de seguridad'),
  ('Barbijo', 'Ferretería general', 'barbijo'),
  ('Protector auditivo', 'Ferretería general', 'protector auditivo'),
  ('Casco de seguridad', 'Ferretería general', 'casco de seguridad'),
  ('Cinto de seguridad', 'Ferretería general', 'cinto de seguridad');
